version: "3.8"

services:
    strapi:
        image: registry.extics.com/thai-merit/thaimerit-cms
        restart: unless-stopped
        container_name: thaimerit-strapi
        volumes:
            - ./public/uploads:/usr/src/app/public/uploads
        env_file: .env
        environment:
            - HOST=$HOST
            - PORT=$PORT
            - PUBLIC_URL=$PUBLIC_URL

            - APP_KEYS=$APP_KEYS
            - API_TOKEN_SALT=$API_TOKEN_SALT
            - ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET
            - JWT_SECRET=$JWT_SECRET

            - DATABASE_HOST=$DATABASE_HOST
            - DATABASE_PORT=$DATABASE_PORT
            - DATABASE_NAME=$DATABASE_NAME
            - DATABASE_USERNAME=$DATABASE_USERNAME
            - DATABASE_PASSWORD=$DATABASE_PASSWORD
            - DATABASE_SSL=$DATABASE_SSL

            - SMTP_HOST=$SMTP_HOST
            - SMTP_PORT=$SMTP_PORT
            - SMTP_USERNAME=$SMTP_USERNAME
            - SMTP_PASSWORD=$SMTP_PASSWORD
        ports:
            - "1337:1337"
